name: "Issue Labeler"
on:
  issues:
    types: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - if: contains(github.event.issue.body, 'New application') == true
        uses: actions-cool/issues-helper@v1.8
        with:
          actions: 'add-labels'
          token: ${{ secrets.GH_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: '💖 Application'
